# fly.toml app configuration file generated for gptfree on 2023-10-12T10:30:49+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gptfree"
primary_region = "hkg"

[build]
  image = "xiangsx/gpt4free-ts:latest"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
